name: Deploy Frontend
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 #pulls the repo code
      - run: docker login -u vastavikprince -p ${{ secrets.DOCKER_HUB_TOKEN }}
      - run: docker build -t prince/react-test -f Dockerfile.dev . #before install
      - run: docker run -e CI=true prince/react-test npm test #what we need to do
